moved to a slightly modified version of onedr0p's script

diff --git a/cloudflare-ddns.yaml b/cloudflare-ddns.yaml
--- a/cloudflare-ddns.yaml
+++ b/cloudflare-ddns.yaml
@@ -1,61 +1,20 @@
-apiVersion: v1
-kind: ConfigMap
-metadata:
-  name: cloudflare-ddns
-  namespace: default
-  labels:
-    app.kubernetes.io/name: cloudflare-ddns
-    app.kubernetes.io/instance: cloudflare-ddns
-data:
-  cloudflare-ddns.sh: |
-    #!/bin/bash
-
-    CF_API_URL="https://api.cloudflare.com/client/v4/zones"
-
-    CF_RECORD=$(curl -sS -X GET \
-      "$CF_API_URL/$CF_ZONE_API_TOKEN/dns_records?type=A" \
-      -H "Authorization: Bearer $CF_DNS_API_TOKEN" \
-      -H "Content-Type: application/json")
-
-    OLDIP=$(echo "$CF_RECORD" | jq -r '.result[].content')
-    IP=$(curl -s icanhazip.com)
-
-    change_record() {
-        ID=$(echo "$CF_RECORD" | jq -r '.result[].id')
-        NAME=$(echo "$CF_RECORD" | jq -r '.result[].name')
-        TYPE=$(echo "$CF_RECORD" | jq -r '.result[].type')
-        TTL=$(echo "$CF_RECORD" | jq -r '.result[].ttl')
-        PROXIED=$(echo "$CF_RECORD" | jq -r '.result[].proxied')
-        curl -sSo /dev/null -X PUT \
-        "$CF_API_URL/$CF_ZONE_API_TOKEN/dns_records/$ID" \
-        -H "Authorization: Bearer $CF_DNS_API_TOKEN" \
-        -H "Content-Type: application/json" \
-        -d "{\"type\":\"${TYPE}\",\"name\":\"${NAME}\",\"content\":\"${IP}\",\"ttl\":\"${TTL}\",\"proxied\":${PROXIED}}"
-    }
-
-    if [[ "$IP" != "$OLDIP" ]]; then
-        change_record
-        echo "[INFO] Updated Cloudflare DNS from "$OLDIP" to "$IP""
-      else
-        echo "[INFO] No DNS update required"
-    fi
-
 ---
 apiVersion: v1
 kind: Secret
 metadata:
   name: cloudflare-api-credentials
-  namespace: default
+  namespace: networking
 type: Opaque
 data:
-  CF_ZONE_API_TOKEN: << put your base64 encoded ZONE api token here >>
-  CF_DNS_API_TOKEN: << put your base64 encoded DNS api token here >>
+  CF_DNS_API_TOKEN: << base64 encoded generated DNS toke >>
+  CF_ZONEID: << base64 encoded zone id >>
+  CF_RECORD_NAME: << base64 encoded domain name >>
 
 ---
 apiVersion: batch/v1
 kind: CronJob
 metadata:
-  namespace: default
+  namespace: networking
   name: cloudflare-ddns
 spec:
   schedule: "0 * * * *"
@@ -69,26 +28,39 @@ spec:
           restartPolicy: Never
           containers:
           - name: cloudflare-ddns
-            image: ghcr.io/jr0dd/cron:latest
+            image: ghcr.io/k8s-at-home/kubectl:v1.21.3
             imagePullPolicy: IfNotPresent
             envFrom:
             - secretRef:
                 name: cloudflare-api-credentials
             command:
-            - "/bin/bash"
-            - "/app/cloudflare-ddns.sh"
-            volumeMounts:
-            - name: cloudflare-ddns
-              mountPath: /app/cloudflare-ddns.sh
-              subPath: cloudflare-ddns.sh
-              readOnly: true
-          volumes:
-          - name: cloudflare-ddns
-            projected:
-              defaultMode: 0775
-              sources:
-              - configMap:
-                  name: cloudflare-ddns
-                  items:
-                  - key: cloudflare-ddns.sh
-                    path: cloudflare-ddns.sh
+            - "/bin/sh"
+            - "-ec"
+            - |
+              set -o nounset
+              set -o errexit
+              ip4=$(curl -s https://ipv4.icanhazip.com/)
+              record4=$(curl -s -X GET \
+                "https://api.cloudflare.com/client/v4/zones/$CF_ZONEID/dns_records?name=$CF_RECORD_NAME&type=A" \
+                -H "Authorization: Bearer $CF_DNS_API_TOKEN" \
+                -H "Content-Type: application/json" \
+              )
+              old_ip4=$(echo "$record4" | sed -n 's/.*"content":"\([^"]*\).*/\1/p')
+              if [ "$ip4" = "$old_ip4" ]; then
+                printf "%s - Success - IP Address '%s' has not changed" "$(date -u)" "$ip4"
+                exit 0
+              fi
+              record4_identifier=$(echo "$record4" | sed -n 's/.*"id":"\([^"]*\).*/\1/p')
+              update4=$(curl -s -X PUT \
+                "https://api.cloudflare.com/client/v4/zones/$CF_ZONEID/dns_records/$record4_identifier" \
+                -H "Authorization: Bearer $CF_DNS_API_TOKEN" \
+                -H "Content-Type: application/json" \
+                --data "{\"id\":\"$CF_ZONEID\",\"type\":\"A\",\"proxied\":true,\"name\":\"$CF_RECORD_NAME\",\"content\":\"$ip4\"}" \
+              )
+              if echo "$update4" | grep -q '\"success\":false'; then
+                printf "%s - Yikes - Updating IP Address '%s' has failed" "$(date -u)" "$ip4"
+                exit 1
+              else
+                printf "%s - Success - IP Address '%s' has been updated" "$(date -u)" "$ip4"
+                exit 0
+              fi
